export interface User {
    id?: number; // Optional since it’s generated by backend
    username: string;
    address: string;
    password: string; // Only sent during creation/update
    mobileno: string; 
    role: string; // e.g., 'USER' or 'ADMIN'
  }