apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chat-mysql-pvc
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi #pls
