export const environment = {
  production: false,
  apiUrl: '/api/chat',
  apiUrlUser: '/api/users',
  websocketUrl: '/ws',
  authApiUrl: '/api/auth',
  authApiUrlService: '/api',
  baseUrlFlashcard: '/api/flashcards',
  apiUrlInvites: '/api/invitations',
  notificationApiUrl: '/api/notifications/send',
  apiUrlResources: '/api/ressources',
  studyGroupApiUrl: '/api',
  apiUrlGroups: '/api/groups',
  openAiApiUrl: '/api/openai',
  baseUrlUser: '/',
  uploadUrl: '/api/Upload',
  apiUrlAi: '/api/ai/generate',
  apiUrlProgress: '/api/progress',
  apiUrlTask: '/api/task',
  apiUrlP: '/api',
};
