export const environment = {
  production: false,
  apiUrl: 'http://chat-service:8082/api/chat',
  apiUrlUser: 'http://user-service:8083/api/users',
  websocketUrl: 'ws://chat-service:8082/ws/chat',
  authApiUrl: 'http://user-service:8083/api/auth',
  authApiUrlService: 'http://user-service:8083/api',
  baseUrlFlashcard: 'http://study-group-service:8081/api/flashcards',
  apiUrlInvites: 'http://study-group-service:8081/api/invitations',
  notificationApiUrl: 'http://study-group-service:8081/api/notifications/send',
  apiUrlResources: 'http://resource-service:8069/api/ressources',
  studyGroupApiUrl: 'http://study-group-service:8081/api',
  apiUrlGroups: 'http://study-group-service:8081/api/groups',
  openAiApiUrl: 'http://study-group-service:8081/api/openai',
  baseUrlUser: 'http://user-service:8083/',
  uploadUrl: 'http://user-service:8083/api/Upload',
  apiUrlAi: 'http://study-group-service:8081/api/ai/generate',
  apiUrlProgress: 'http://task-service:9098/api/progress',
  apiUrlTask: 'http://task-service:9098/api/task',
  apiUrlP: '/api',
};
