spring.application.name=chat-service

spring.datasource.url=jdbc:postgresql://localhost:5432/chat_service
spring.datasource.username=postgres
spring.datasource.password=changeme
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.kafka.bootstrap-servers=localhost:9092

spring.jpa.show-sql=true

server.port=9099
