apiVersion: v1
kind: Service
metadata:
  name: study-group-service
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081
  selector:
    app: study-group-service
