apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: bapo12/user-service:latest
          ports:
            - containerPort: 8083  # Updated from 8080 to 8083
          envFrom:
            - secretRef:
                name: user-service-secrets #name