apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8083           # Exposed service port
      targetPort: 8083     # Container port
      nodePort: 30083      # Exposed on the node
  type: NodePort
