name: Build and Push Frontend Docker Image

on:
  push:
    branches: [ production ]
    paths:
      - 'frontend/**'  # Only run when frontend files change

jobs:
  build:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Frontend Docker Image
        uses: docker/build-push-action@v2
        with:
          context: frontend
          file: frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/studybuddy-frontend:latest,${{ secrets.DOCKER_USERNAME }}/studybuddy-frontend:${{ github.sha }}

      - name: Clean up unused Docker images
        run: |
          docker system prune -f
          docker image prune -f
