name: Build GitHub Actions Runner Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main  # Trigger the workflow on PR to `main` branch

jobs:
  build:
    runs-on: ubuntu-latest  # The runner runs on an Ubuntu machine

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Your Docker Hub username (stored in GitHub Secrets)
          password: ${{ secrets.DOCKER_PASSWORD }}  # Your Docker Hub password (stored in GitHub Secrets)

      - name: Build the Docker image
        run: |
          docker build -t bapo12/github-actions-runner:${{ github.sha }} .
          docker tag bapo12/github-actions-runner:${{ github.sha }} bapo12/github-actions-runner:latest

      - name: Push the Docker image to Docker Hub
        run: |
          docker push bapo12/github-actions-runner:${{ github.sha }}
          docker push bapo12/github-actions-runner:latest
