name: Deploy User Service to Kubernetes

on:
  push:
    branches: [ production ]
    paths:
      - 'backend/user-service/**'   # Only run when user-service changes

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

      - name: Deploy user-service
        run: |
          kubectl apply -f backend/user-service/user-service-deployment.yaml --validate=false
          kubectl apply -f backend/user-service/user-service-service.yaml --validate=false
