name: Deploy User Service to Kubernetes

on:
  push:
    branches:
      - production
    paths:
      - 'backend/user-service/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Kubeconfig
        uses: azure/setup-kubectl@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f backend/user-service/user-service-deployment.yaml
          kubectl apply -f backend/user-service/user-service-service.yaml
