name: Deploy MySQL for User Service

on:
  push:
    branches: [ production ]
    paths:
      - 'backend/user-service/**'   # Only run when user-service changes

jobs:
  deploy-mysql:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

      - name: Deploy PVC, Deployment, and Service
        run: |
          kubectl apply -f backend/user-service/mysql/mysql-pvc.yaml --validate=false
          kubectl apply -f backend/user-service/mysql/mysql-deployment.yaml --validate=false
          kubectl apply -f backend/user-service/mysql/mysql-service.yaml --validate=false
