name: Build and Push user-service Docker Image

on:
  push:
    branches: [ production ]
    paths:
      - 'backend/user-service/**'   # Only run when user-service changes

jobs:
  build:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: backend/user-service

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Spring Boot JAR
        run: mvn clean package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          sudo docker buildx build --push --tag ${{ secrets.DOCKER_USERNAME }}/user-service:latest backend/user-service
