name: Deploy User Service to Kubernetes

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Create kubeconfig from secret
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Test kubectl access
        run: |
          kubectl config view
          kubectl get nodes

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f backend/user-service/user-service-deployment.yaml
          kubectl apply -f backend/user-service/user-service-service.yaml

      - name: Show deployed services
        run: |
          kubectl get pods,svc